spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 3000
  compression:
    enabled: true
  error:
    include-message: always
  shutdown: "graceful"

openweathermap:
  api:
    key: f6b9dc9f856b4ab946f4acb7314857a1
    url: https://api.openweathermap.org/data/2.5